# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Finance
  items:
    - label: 'Intro'
      link: '/finance/intro'
    - label: 'Dataset'
      link: '/finance/data'
    - label: 'Biased model'
      link: '/finance/biased-model'
    - label: 'Interventions'
      link: '/finance/interventions'
    - label: 'Conclusion'
      link: '/finance/conclusion'
- label: Recruiting
  items:
    - label: 'Intro'
      link: '/recruiting/intro'
    - label: 'Dataset'
      link: '/recruiting/data'
