# Sidebar navigation
- label: Home
  link: /
- label: About PETs
  items:
    - label: What are PETs?
      link: /what-are-pets
- label: Technologies
  items:
    - label: De-identification techniques
      link: /de-id
    - label: Homomorphic Encryption
      link: /he
    - label: Trusted Execution Environments
      link: /tees
    - label: Multi-Party Computation
      link: /mpc
    - label: Federated Analytics
      link: /fa
    - label: Differential Privacy
      link: /dp
- label: PETs Adoption Guide
  items:
    - label: The Guide
      link: /adoption-guide
    - label: Repository of Use Cases
      link: /repository

- label: Privacy policy
  items:
    - label: Cookie Policy
      link: /cookie-policy
    - label: Privacy Notice
      link: /privacy-notice
