# Sidebar navigation

- label: Use cases
  items:
    - label: Finance
      link: /finance
    - label: Recruiting
      link: /recruiting
- label: Modelling
  items:
    - label: Unfair baseline
      link: /baseline
    - label: Interventions
      link: /interventions
- label: Conclusions
  link: /conclusion
