# Sidebar navigation

- label: Overview
  link: /
- label: Use cases
  items:
    - label: Finance
      link: /finance
    - label: Recruiting
      link: /recruiting
- label: Modelling
  items:
    - label: Biased models
      link: /biased-models
    - label: Interventions
      link: /interventions
- label: Conclusions
  link: /conclusion
