# Sidebar navigation
- label: Home
  link: /
- label: Use Cases
  items:
    - label: Finance
      link: /finance
    - label: Recruiting
      link: /recruiting
- label: Modelling
  items:
    - label: Unfair Baseline
      link: /baseline
    - label: Interventions
      link: /interventions
- label: Summary
  items:
    - label: Conclusions
      link: /conclusions
    - label: Additional Resources
      link: /additional-resources
- label: Privacy
  items:
    - label: Cookie Policy
      link: /cookie-policy
    - label: Privacy Notice
      link: /privacy-notice
