# Sidebar navigation
- label: Home
  link: /
- label: Background
  link: /background
- label: Repository of Use Cases
  link: /repository
- label: Glossary
  link: /glossary
- label: Additional resources
  link: /additional-resources
- label: Future work
  link: /future-work
- label: Privacy policy
  items:
    - label: Cookie Policy
      link: /cookie-policy
    - label: Privacy Notice
      link: /privacy-notice
