name: Linting

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/lint.yml'

jobs:
  node-lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        make-lint: ["site-format-check"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Node dependencies
        working-directory: src/site
        run: npm install

      - name: Lint with ${{ matrix.make-lint }}
        working-directory: src/
        run: |
          make ${{ matrix.make-lint }}
