name: Clean and Release Notebooks

on:
  push:
    branches:
      - master

jobs:
  clean-notebook:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-pipeline.txt

      - name: Remove superfluous cells
        working-directory: src/notebooks
        run: |
          mkdir -p ../../notebooks
          nb-filter-cells -i adult.ipynb -o ../../notebooks/adult.ipynb -t export
          mkdir -p ../../notebooks/finance
          nb-filter-cells -i finance/adversarial-debiasing.ipynb -o ../../notebooks/finance/adversarial-debiasing.ipynb -t export

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Commit cleaned notebook

          # Optional options appended to `git-commit`
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          file_pattern: notebooks/*.ipynb

          # Optional local file path to the repository
          repository: .

          # Optional options appended to `git-push`
          push_options: '--force'
