name: Build and Deploy Site

on:
  push:
    branch:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt
          python3 -m pip install -r ./requirements-pipeline.txt

      - name: Build Plots
        working-directory: src/
        run: |
          jupyter nbconvert --to python adult.ipynb
          python3 adult.py
          mkdir -p ../site/src/figures/
          mv *.json ../site/src/figures

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Node dependencies
        working-directory: site/
        run: npm install

      - name: Build Site
        working-directory: site/
        run: |
          npm run-script build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public

